///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace op_app_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The add_payment_pg5 recording.
    /// </summary>
    [TestModule("f3d1dbd4-1fe7-4ea3-a3d6-1328298b842e", ModuleType.Recording, 1)]
    public partial class add_payment_pg5 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the op_app_demoRepository repository.
        /// </summary>
        public static op_app_demoRepository repo = op_app_demoRepository.Instance;

        static add_payment_pg5 instance = new add_payment_pg5();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public add_payment_pg5()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static add_payment_pg5 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1NrPhysicianOwnership' at 10;14.", repo.ApplicationUnderTest.Form1NrPhysicianOwnershipInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Form1NrPhysicianOwnership.Click("10;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '3' on item 'ApplicationUnderTest.Form1NrThirdPartyPaymentRecipientIndica'.", repo.ApplicationUnderTest.Form1NrThirdPartyPaymentRecipientIndicaInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Form1NrThirdPartyPaymentRecipientIndica.Element.SetAttributeValue("TagValue", "3");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'N' on item 'ApplicationUnderTest.Form1CharityIndicator'.", repo.ApplicationUnderTest.Form1CharityIndicatorInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Form1CharityIndicator.Element.SetAttributeValue("TagValue", "N");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '3' on item 'ApplicationUnderTest.Form1NrResearchDelayinPublicationofRese'.", repo.ApplicationUnderTest.Form1NrResearchDelayinPublicationofReseInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Form1NrResearchDelayinPublicationofRese.Element.SetAttributeValue("TagValue", "3");
            Delay.Milliseconds(20);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1ContinueBtn' at Center.", repo.ApplicationUnderTest.Form1ContinueBtnInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.Form1ContinueBtn.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(5));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1ContinueButton' at Center.", repo.ApplicationUnderTest.Form1ContinueButtonInfo, new RecordItemIndex(6));
            //repo.ApplicationUnderTest.Form1ContinueButton.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'ApplicationUnderTest.Form1ContinueButton'.", repo.ApplicationUnderTest.Form1ContinueButtonInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Form1ContinueButton.PerformClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
