///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace op_app_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The add_payment_pg2 recording.
    /// </summary>
    [TestModule("4e744321-680e-4334-9ba8-19f890305464", ModuleType.Recording, 1)]
    public partial class add_payment_pg2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the op_app_demoRepository repository.
        /// </summary>
        public static op_app_demoRepository repo = op_app_demoRepository.Instance;

        static add_payment_pg2 instance = new add_payment_pg2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public add_payment_pg2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static add_payment_pg2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'ApplicationUnderTest.Form1CoveredRecipientType'.", repo.ApplicationUnderTest.Form1CoveredRecipientTypeInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Form1CoveredRecipientType.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1NrPhysicianFirst' at 31;15.", repo.ApplicationUnderTest.Form1NrPhysicianFirstInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Form1NrPhysicianFirst.Click("31;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'op' with focus on 'ApplicationUnderTest.Form1NrPhysicianFirst'.", repo.ApplicationUnderTest.Form1NrPhysicianFirstInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Form1NrPhysicianFirst.PressKeys("op");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1NrPhysicianLast' at 55;18.", repo.ApplicationUnderTest.Form1NrPhysicianLastInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Form1NrPhysicianLast.Click("55;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'jones' with focus on 'ApplicationUnderTest.Form1NrPhysicianLast'.", repo.ApplicationUnderTest.Form1NrPhysicianLastInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Form1NrPhysicianLast.PressKeys("jones");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'US' on item 'ApplicationUnderTest.Form1NonresearchCountryPhy'.", repo.ApplicationUnderTest.Form1NonresearchCountryPhyInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Form1NonresearchCountryPhy.Element.SetAttributeValue("TagValue", "US");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1NrAddress1' at 48;14.", repo.ApplicationUnderTest.Form1NrAddress1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Form1NrAddress1.Click("48;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '321 park lane' with focus on 'ApplicationUnderTest.Form1NrAddress1'.", repo.ApplicationUnderTest.Form1NrAddress1Info, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Form1NrAddress1.PressKeys("321 park lane");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1NrCity' at Center.", repo.ApplicationUnderTest.Form1NrCityInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Form1NrCity.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fairfax' with focus on 'ApplicationUnderTest.Form1NrCity'.", repo.ApplicationUnderTest.Form1NrCityInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.Form1NrCity.EnsureVisible();
            Keyboard.Press("fairfax");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'VA' on item 'ApplicationUnderTest.Form1NrState'.", repo.ApplicationUnderTest.Form1NrStateInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.Form1NrState.Element.SetAttributeValue("TagValue", "VA");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1RecipientZipCodeGnrl' at 49;20.", repo.ApplicationUnderTest.Form1RecipientZipCodeGnrlInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.Form1RecipientZipCodeGnrl.Click("49;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '22033' with focus on 'ApplicationUnderTest.Form1RecipientZipCodeGnrl'.", repo.ApplicationUnderTest.Form1RecipientZipCodeGnrlInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.Form1RecipientZipCodeGnrl.PressKeys("22033");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'ApplicationUnderTest.Form1NrPrimaryType'.", repo.ApplicationUnderTest.Form1NrPrimaryTypeInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.Form1NrPrimaryType.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1PhySpecGnrlInput' at 81;19.", repo.ApplicationUnderTest.Form1PhySpecGnrlInputInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.Form1PhySpecGnrlInput.Click("81;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '111nI0013X' with focus on 'ApplicationUnderTest.Form1PhySpecGnrlInput'.", repo.ApplicationUnderTest.Form1PhySpecGnrlInputInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.Form1PhySpecGnrlInput.PressKeys("111nI0013X");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1StLicGnrl' at 272;19.", repo.ApplicationUnderTest.Form1StLicGnrlInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.Form1StLicGnrl.Click("272;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Next}{Next}{Next}{Next}{Next}' with focus on 'ApplicationUnderTest.Form1StLicGnrl'.", repo.ApplicationUnderTest.Form1StLicGnrlInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.Form1StLicGnrl.PressKeys("{Next}{Next}{Next}{Next}{Next}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Firefox.Virginia' at 71;16.", repo.Firefox.VirginiaInfo, new RecordItemIndex(18));
            repo.Firefox.Virginia.Click("71;16");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1StLicGnrl' at Center.", repo.ApplicationUnderTest.Form1StLicGnrlInfo, new RecordItemIndex(19));
            //repo.ApplicationUnderTest.Form1StLicGnrl.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1Nrlicense1' at 57;26.", repo.ApplicationUnderTest.Form1Nrlicense1Info, new RecordItemIndex(20));
            repo.ApplicationUnderTest.Form1Nrlicense1.Click("57;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0013' with focus on 'ApplicationUnderTest.Form1Nrlicense1'.", repo.ApplicationUnderTest.Form1Nrlicense1Info, new RecordItemIndex(21));
            repo.ApplicationUnderTest.Form1Nrlicense1.PressKeys("0013");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1RoleButton' at 29;17.", repo.ApplicationUnderTest.Form1RoleButtonInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.Form1RoleButton.Click("29;17");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1ContinueButton' at 65;15.", repo.ApplicationUnderTest.Form1ContinueButtonInfo, new RecordItemIndex(23));
            //repo.ApplicationUnderTest.Form1ContinueButton.Click("65;15");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'ApplicationUnderTest.Form1ContinueButton'.", repo.ApplicationUnderTest.Form1ContinueButtonInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.Form1ContinueButton.PerformClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
