///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace op_app_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The add_payment_review_pg recording.
    /// </summary>
    [TestModule("443bd38d-dd40-4e09-85a2-79136bb7cefe", ModuleType.Recording, 1)]
    public partial class add_payment_review_pg : ITestModule
    {
        /// <summary>
        /// Holds an instance of the op_app_demoRepository repository.
        /// </summary>
        public static op_app_demoRepository repo = op_app_demoRepository.Instance;

        static add_payment_review_pg instance = new add_payment_review_pg();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public add_payment_review_pg()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static add_payment_review_pg Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1453 units.", new RecordItemIndex(1));
            Mouse.ScrollWheel(-1453);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(2));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1ContinueButton' at 64;8.", repo.ApplicationUnderTest.Form1ContinueButtonInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Form1ContinueButton.Click("64;8");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'ApplicationUnderTest.Form1ContinueButton'.", repo.ApplicationUnderTest.Form1ContinueButtonInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.Form1ContinueButton.PerformClick();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.Form1Ns0x002fopenpayments0x002fOpen0x01'.", repo.ApplicationUnderTest.Form1Ns0x002fopenpayments0x002fOpen0x01Info, new RecordItemIndex(5));
            Validate.Exists(repo.ApplicationUnderTest.Form1Ns0x002fopenpayments0x002fOpen0x01Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
