///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace op_app_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The add_payment_pg4 recording.
    /// </summary>
    [TestModule("f49928a8-56f5-458a-8ace-3eeffac5f5fb", ModuleType.Recording, 1)]
    public partial class add_payment_pg4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the op_app_demoRepository repository.
        /// </summary>
        public static op_app_demoRepository repo = op_app_demoRepository.Instance;

        static add_payment_pg4 instance = new add_payment_pg4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public add_payment_pg4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static add_payment_pg4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1NrTotalAmount' at 24;11.", repo.ApplicationUnderTest.Form1NrTotalAmountInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Form1NrTotalAmount.Click("24;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '500.00' with focus on 'ApplicationUnderTest.Form1NrTotalAmount'.", repo.ApplicationUnderTest.Form1NrTotalAmountInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Form1NrTotalAmount.PressKeys("500.00");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1PaymentDate' at 76;19.", repo.ApplicationUnderTest.Form1PaymentDateInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Form1PaymentDate.Click("76;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '20180501' with focus on 'ApplicationUnderTest.Form1PaymentDate'.", repo.ApplicationUnderTest.Form1PaymentDateInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Form1PaymentDate.PressKeys("20180501");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1PaymentCount' at 88;12.", repo.ApplicationUnderTest.Form1PaymentCountInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Form1PaymentCount.Click("88;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Form1PaymentCount'.", repo.ApplicationUnderTest.Form1PaymentCountInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Form1PaymentCount.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'ApplicationUnderTest.Form1NrFormofPaymentorTransferofValue20'.", repo.ApplicationUnderTest.Form1NrFormofPaymentorTransferofValue20Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Form1NrFormofPaymentorTransferofValue20.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'ApplicationUnderTest.Form1NrNonResearchNatureofPaymentorTran'.", repo.ApplicationUnderTest.Form1NrNonResearchNatureofPaymentorTranInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Form1NrNonResearchNatureofPaymentorTran.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(20);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(8));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form1ContinueButton' at 64;19.", repo.ApplicationUnderTest.Form1ContinueButtonInfo, new RecordItemIndex(9));
            //repo.ApplicationUnderTest.Form1ContinueButton.Click("64;19");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'ApplicationUnderTest.Form1ContinueButton'.", repo.ApplicationUnderTest.Form1ContinueButtonInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.Form1ContinueButton.PerformClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
