///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace op_app_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the op_app_demoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("fc2b0a9a-96d6-49f4-b64a-8c5a78819d5c")]
    public partial class op_app_demoRepository : RepoGenBaseFolder
    {
        static op_app_demoRepository instance = new op_app_demoRepository();
        op_app_demoRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        op_app_demoRepositoryFolders.FirefoxAppFolder _firefox;

        /// <summary>
        /// Gets the singleton class instance representing the op_app_demoRepository element repository.
        /// </summary>
        [RepositoryFolder("fc2b0a9a-96d6-49f4-b64a-8c5a78819d5c")]
        public static op_app_demoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public op_app_demoRepository() 
            : base("op_app_demoRepository", "/", null, 0, false, "fc2b0a9a-96d6-49f4-b64a-8c5a78819d5c", ".\\RepositoryImages\\op_app_demoRepositoryfc2b0a9a.rximgres")
        {
            _applicationundertest = new op_app_demoRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _firefox = new op_app_demoRepositoryFolders.FirefoxAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fc2b0a9a-96d6-49f4-b64a-8c5a78819d5c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("3ecc3f31-ca83-4d4a-b904-08852327c04a")]
        public virtual op_app_demoRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Firefox folder.
        /// </summary>
        [RepositoryFolder("e7c2dfdf-c7b2-4aa9-902e-bd37bc07b046")]
        public virtual op_app_demoRepositoryFolders.FirefoxAppFolder Firefox
        {
            get { return _firefox; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class op_app_demoRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("3ecc3f31-ca83-4d4a-b904-08852327c04a")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginInfo;
            RepoItemInfo _useridInfo;
            RepoItemInfo _nsz7cgah47l008lg50iahur9q330u1loginInfo;
            RepoItemInfo _tdtagoppInfo;
            RepoItemInfo _httpop2opv3dev110039wpswsrpproxyInfo;
            RepoItemInfo _form1ns0x002fopenpayments0x002fopen0x0Info;
            RepoItemInfo _form1paymenttypeInfo;
            RepoItemInfo _form1paymentreportentityInfo;
            RepoItemInfo _form1programyearInfo;
            RepoItemInfo _form1continuebuttonInfo;
            RepoItemInfo _form1coveredrecipienttypeInfo;
            RepoItemInfo _form1nrphysicianfirstInfo;
            RepoItemInfo _form1nrphysicianlastInfo;
            RepoItemInfo _form1nraddress1Info;
            RepoItemInfo _form1nrstateInfo;
            RepoItemInfo _form1recipientzipcodegnrlInfo;
            RepoItemInfo _form1nrprimarytypeInfo;
            RepoItemInfo _someptagInfo;
            RepoItemInfo _form1physpecgnrlinputInfo;
            RepoItemInfo _formrowgrid225Info;
            RepoItemInfo _form1nrlicense1Info;
            RepoItemInfo _form1rolebuttonInfo;
            RepoItemInfo _form1productindInfo;
            RepoItemInfo _form1continuebtnInfo;
            RepoItemInfo _form1nrtotalamountInfo;
            RepoItemInfo _form1paymentdateInfo;
            RepoItemInfo _form1paymentcountInfo;
            RepoItemInfo _form1nrformofpaymentortransferofvalue20Info;
            RepoItemInfo _form1nrnonresearchnatureofpaymentortranInfo;
            RepoItemInfo _form1nrphysicianownershipInfo;
            RepoItemInfo _form1nrthirdpartypaymentrecipientindicaInfo;
            RepoItemInfo _form1charityindicatorInfo;
            RepoItemInfo _form1nrresearchdelayinpublicationofreseInfo;
            RepoItemInfo _grid1000Info;
            RepoItemInfo _form1ns0x002fopenpayments0x002fopen0x01Info;
            RepoItemInfo _form1stlicgnrlInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _oppsitInfo;
            RepoItemInfo _form1nonresearchcountryphyInfo;
            RepoItemInfo _form1nrcityInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='op2-op-v3dev1:10039']", parentFolder, 30000, null, false, "3ecc3f31-ca83-4d4a-b904-08852327c04a", "")
            {
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//div[#'CommonActionsList']//a[@innertext='Log In']", 30000, null, "02ebb1e1-9bd6-4267-8b2f-b62c626b4800");
                _useridInfo = new RepoItemInfo(this, "UserID", ".//input[#'userID']", 30000, null, "dfa1a155-307c-4403-ac93-ec49c5af2807");
                _nsz7cgah47l008lg50iahur9q330u1loginInfo = new RepoItemInfo(this, "NsZ7CGAH47L008LG50IAHUR9Q330U1Login", ".//input[@name<'login']", 30000, null, "4abe827b-b01e-490d-8235-29d6d0005388");
                _tdtagoppInfo = new RepoItemInfo(this, "TdTagOPP", "body/div[7]/table//td[@innertext='OPP']", 30000, null, "bea45b33-d37e-4f28-8840-5084d7cbcda4");
                _httpop2opv3dev110039wpswsrpproxyInfo = new RepoItemInfo(this, "HttpOp2OpV3dev110039WpsWsrpProxy", ".//form[#'form1']/div/div/div[2]/div/div/ul/li[2]/a[@title='Submit, Review, Attest']/img[@src='http://op2-op-v3dev1:10039/wps/WsrpProxyPortlet/ResourceProxy/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48dT48Yj5odHRwOi8vb3AyLW9wLWFwcDI6OTA4MDwvYj48cD48bj5wPC9uPjx2PloxMl9VUlBVOEIxQTA4TTc4MFFDU01INExIMzBHMzwvdj48L3A-PHA-PG4-d3NycC1zZWN1cmVVUkw8L24-PHY-ZmFsc2U8L3Y-PC9wPjxwPjxuPndzcnAtdXJsVHlwZTwvbj48dj5yZXNvdXJjZTwvdj48L3A-PC91Pg!!/9EpxCbFiczQfnKyuhmsxSAJw7l0!/openpayments/faces/javax.faces.resource/theme/img/submissionsIcon.png']", 30000, null, "68d28175-b2c7-4528-86f3-f8d83898d183");
                _form1ns0x002fopenpayments0x002fopen0x0Info = new RepoItemInfo(this, "Form1Ns0x002fopenpayments0x002fOpen0x0", ".//form[#'form1']/div/div/div[3]/div[3]/div/div[1]/div/div[2]/?/?/input[@name='form1:ns_0x002fopenpayments0x002fOpen0x0020Payments0x0020Registration0x002f7_URPU8B1A08G9E0QCSHPUJV00C2_j_id1210228733_48229eba']", 30000, null, "aa4854a5-fb59-445d-b875-6a7ece1d72e0");
                _form1paymenttypeInfo = new RepoItemInfo(this, "Form1PaymentType", ".//select[#'form1:paymentType']", 30000, null, "205a490a-063f-4568-bda8-721c23f52dc3");
                _form1paymentreportentityInfo = new RepoItemInfo(this, "Form1Paymentreportentity", ".//select[#'form1:paymentreportentity']", 30000, null, "a38e0c6e-7dee-41f3-964b-bccf107e8849");
                _form1programyearInfo = new RepoItemInfo(this, "Form1ProgramYear", ".//select[#'form1:programYear']", 30000, null, "bba8154e-9857-403f-9d85-c882e60d79f4");
                _form1continuebuttonInfo = new RepoItemInfo(this, "Form1ContinueButton", ".//input[#'form1:continueButton']", 30000, null, "6a18858f-0bdb-4bce-bd69-3b56be5a80b1");
                _form1coveredrecipienttypeInfo = new RepoItemInfo(this, "Form1CoveredRecipientType", ".//select[#'form1:coveredRecipientType']", 30000, null, "4b3d5c1c-9786-4847-b79d-52ca981c31cc");
                _form1nrphysicianfirstInfo = new RepoItemInfo(this, "Form1NrPhysicianFirst", ".//input[#'form1:nrPhysicianFirst']", 30000, null, "d2460586-704a-4a20-b7c6-3b12f47fff08");
                _form1nrphysicianlastInfo = new RepoItemInfo(this, "Form1NrPhysicianLast", ".//input[#'form1:nrPhysicianLast']", 30000, null, "32173683-6b5d-4c95-ab40-b6195c89f2d8");
                _form1nraddress1Info = new RepoItemInfo(this, "Form1NrAddress1", ".//div[#'form1:fieldGroup']/div/?/?/fieldset/div[2]/?/?/input[@name='form1:nrAddress1']", 30000, null, "ba9847f0-1170-4467-838f-d137ee0da14e");
                _form1nrstateInfo = new RepoItemInfo(this, "Form1NrState", ".//select[#'form1:nrState']", 30000, null, "0f589392-2158-47e7-b4a9-16c30ba7d28d");
                _form1recipientzipcodegnrlInfo = new RepoItemInfo(this, "Form1RecipientZipCodeGnrl", ".//input[#'form1:recipientZipCodeGnrl']", 30000, null, "a2840ba3-a5ff-4746-b3fe-c6e9f84280fc");
                _form1nrprimarytypeInfo = new RepoItemInfo(this, "Form1NrPrimaryType", ".//select[#'form1:nrPrimaryType']", 30000, null, "a0e0e6da-84ce-4164-a2aa-a219b578a803");
                _someptagInfo = new RepoItemInfo(this, "SomePTag", ".//div[#'form1:licenseContent']/?/?/p", 30000, null, "c53a8161-9d2d-4280-aa84-cecd27b1790b");
                _form1physpecgnrlinputInfo = new RepoItemInfo(this, "Form1PhySpecGnrlInput", ".//span[#'form1:phySpecGnrl']/input[@name='form1:phySpecGnrl_input']", 30000, null, "6b36eea0-2743-4a4e-b341-81ef49434573");
                _formrowgrid225Info = new RepoItemInfo(this, "FormRowGrid225", ".//span[#'form1:licenseGrpPanel']/span/span[1]", 30000, null, "6a3819bf-594c-4010-86cb-a6c108e242f4");
                _form1nrlicense1Info = new RepoItemInfo(this, "Form1Nrlicense1", ".//span[#'form1:licenseGrpPanel']//input[@name='form1:nrlicense1']", 30000, null, "16366e6b-790b-4c6d-bdf6-234f5d32a8ad");
                _form1rolebuttonInfo = new RepoItemInfo(this, "Form1RoleButton", ".//input[#'form1:roleButton']", 30000, null, "c0c5f4fb-eed7-4c34-ad9c-63c2ce6a65a0");
                _form1productindInfo = new RepoItemInfo(this, "Form1ProductInd", ".//select[#'form1:productInd']", 30000, null, "e9e735b8-b5eb-4c5e-9ce9-0a23d349c708");
                _form1continuebtnInfo = new RepoItemInfo(this, "Form1ContinueBtn", ".//input[#'form1:continueBtn']", 30000, null, "84a1741f-12dd-4e41-8043-ca6a53513e30");
                _form1nrtotalamountInfo = new RepoItemInfo(this, "Form1NrTotalAmount", ".//input[#'form1:nrTotalAmount']", 30000, null, "abe71b8a-6ec4-46b6-8081-0688171fc660");
                _form1paymentdateInfo = new RepoItemInfo(this, "Form1PaymentDate", ".//input[#'form1:paymentDate']", 30000, null, "8b11133c-011e-4b2b-a613-dedb0589d23a");
                _form1paymentcountInfo = new RepoItemInfo(this, "Form1PaymentCount", ".//input[#'form1:paymentCount']", 30000, null, "558a31ec-9f39-4a43-b75a-d97944527b23");
                _form1nrformofpaymentortransferofvalue20Info = new RepoItemInfo(this, "Form1NrFormofPaymentorTransferofValue20", ".//form[#'form1']/div[1]/div[1]/div[2]/div[2]/div[4]/div/div[4]//select[@name='form1:nrFormofPaymentorTransferofValue2016']", 30000, null, "bd290590-ae4f-46a5-adb3-46d894966c56");
                _form1nrnonresearchnatureofpaymentortranInfo = new RepoItemInfo(this, "Form1NrNonResearchNatureofPaymentorTran", ".//select[#'form1:nrNonResearchNatureofPaymentorTransferofValueb']", 30000, null, "cd015676-7508-48bd-9440-60840913e498");
                _form1nrphysicianownershipInfo = new RepoItemInfo(this, "Form1NrPhysicianOwnership", ".//table[#'form1:nrPhysicianOwnership']/?/?/tr/td[2]/input[@name='form1:nrPhysicianOwnership']", 30000, null, "e488c9f1-6d34-466a-8ed1-80c16b2f6547");
                _form1nrthirdpartypaymentrecipientindicaInfo = new RepoItemInfo(this, "Form1NrThirdPartyPaymentRecipientIndica", ".//select[#'form1:nrThirdPartyPaymentRecipientIndicator']", 30000, null, "4aaca5e0-54d2-4400-b508-ce666ca9c8ca");
                _form1charityindicatorInfo = new RepoItemInfo(this, "Form1CharityIndicator", ".//select[#'form1:charityIndicator']", 30000, null, "63255ec9-6c01-4667-a442-86db50f2982d");
                _form1nrresearchdelayinpublicationofreseInfo = new RepoItemInfo(this, "Form1NrResearchDelayinPublicationofRese", ".//select[#'form1:nrResearchDelayinPublicationofResearchPaymentIndicator']", 30000, null, "3ac563e5-4212-4c31-baf4-af636ac49d37");
                _grid1000Info = new RepoItemInfo(this, "Grid1000", ".//form[#'form1']/div[1]/div/div[2]/div[2]/div[4]/div[5]/p[3]", 30000, null, "2c420f82-b57b-4e44-b1ed-6c7a81527279");
                _form1ns0x002fopenpayments0x002fopen0x01Info = new RepoItemInfo(this, "Form1Ns0x002fopenpayments0x002fOpen0x01", ".//h1[#'focusH1']/span[@innertext='Record Saved Successfully']", 30000, null, "e1db649a-041b-4a79-adfe-34382458b4b3");
                _form1stlicgnrlInfo = new RepoItemInfo(this, "Form1StLicGnrl", ".//select[#'form1:stLicGnrl']", 30000, null, "c00062db-705a-4a14-b838-debfa94c5600");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "d9eb99d0-2659-45d6-9b7d-e09f233b8924");
                _oppsitInfo = new RepoItemInfo(this, "OPPSIT", ".//div[#'navTabs']/ul//a[@innertext='OPP_SIT']", 30000, null, "21c8f28e-cbf5-4889-9469-f5f6a2be3276");
                _form1nonresearchcountryphyInfo = new RepoItemInfo(this, "Form1NonresearchCountryPhy", ".//select[#'form1:nonresearchCountryPhy']", 30000, null, "a54196b7-bf21-47b7-b035-e85cfde21eca");
                _form1nrcityInfo = new RepoItemInfo(this, "Form1NrCity", ".//input[#'form1:nrCity']", 30000, null, "f57646a7-39ca-4fef-81ee-3d8a112297eb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3ecc3f31-ca83-4d4a-b904-08852327c04a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ecc3f31-ca83-4d4a-b904-08852327c04a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("02ebb1e1-9bd6-4267-8b2f-b62c626b4800")]
            public virtual Ranorex.ATag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("02ebb1e1-9bd6-4267-8b2f-b62c626b4800")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The UserID item.
            /// </summary>
            [RepositoryItem("dfa1a155-307c-4403-ac93-ec49c5af2807")]
            public virtual Ranorex.InputTag UserID
            {
                get
                {
                    return _useridInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserID item info.
            /// </summary>
            [RepositoryItemInfo("dfa1a155-307c-4403-ac93-ec49c5af2807")]
            public virtual RepoItemInfo UserIDInfo
            {
                get
                {
                    return _useridInfo;
                }
            }

            /// <summary>
            /// The NsZ7CGAH47L008LG50IAHUR9Q330U1Login item.
            /// </summary>
            [RepositoryItem("4abe827b-b01e-490d-8235-29d6d0005388")]
            public virtual Ranorex.InputTag NsZ7CGAH47L008LG50IAHUR9Q330U1Login
            {
                get
                {
                    return _nsz7cgah47l008lg50iahur9q330u1loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NsZ7CGAH47L008LG50IAHUR9Q330U1Login item info.
            /// </summary>
            [RepositoryItemInfo("4abe827b-b01e-490d-8235-29d6d0005388")]
            public virtual RepoItemInfo NsZ7CGAH47L008LG50IAHUR9Q330U1LoginInfo
            {
                get
                {
                    return _nsz7cgah47l008lg50iahur9q330u1loginInfo;
                }
            }

            /// <summary>
            /// The TdTagOPP item.
            /// </summary>
            [RepositoryItem("bea45b33-d37e-4f28-8840-5084d7cbcda4")]
            public virtual Ranorex.TdTag TdTagOPP
            {
                get
                {
                    return _tdtagoppInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TdTagOPP item info.
            /// </summary>
            [RepositoryItemInfo("bea45b33-d37e-4f28-8840-5084d7cbcda4")]
            public virtual RepoItemInfo TdTagOPPInfo
            {
                get
                {
                    return _tdtagoppInfo;
                }
            }

            /// <summary>
            /// The HttpOp2OpV3dev110039WpsWsrpProxy item.
            /// </summary>
            [RepositoryItem("68d28175-b2c7-4528-86f3-f8d83898d183")]
            public virtual Ranorex.ImgTag HttpOp2OpV3dev110039WpsWsrpProxy
            {
                get
                {
                    return _httpop2opv3dev110039wpswsrpproxyInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpOp2OpV3dev110039WpsWsrpProxy item info.
            /// </summary>
            [RepositoryItemInfo("68d28175-b2c7-4528-86f3-f8d83898d183")]
            public virtual RepoItemInfo HttpOp2OpV3dev110039WpsWsrpProxyInfo
            {
                get
                {
                    return _httpop2opv3dev110039wpswsrpproxyInfo;
                }
            }

            /// <summary>
            /// The Form1Ns0x002fopenpayments0x002fOpen0x0 item.
            /// </summary>
            [RepositoryItem("aa4854a5-fb59-445d-b875-6a7ece1d72e0")]
            public virtual Ranorex.InputTag Form1Ns0x002fopenpayments0x002fOpen0x0
            {
                get
                {
                    return _form1ns0x002fopenpayments0x002fopen0x0Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1Ns0x002fopenpayments0x002fOpen0x0 item info.
            /// </summary>
            [RepositoryItemInfo("aa4854a5-fb59-445d-b875-6a7ece1d72e0")]
            public virtual RepoItemInfo Form1Ns0x002fopenpayments0x002fOpen0x0Info
            {
                get
                {
                    return _form1ns0x002fopenpayments0x002fopen0x0Info;
                }
            }

            /// <summary>
            /// The Form1PaymentType item.
            /// </summary>
            [RepositoryItem("205a490a-063f-4568-bda8-721c23f52dc3")]
            public virtual Ranorex.SelectTag Form1PaymentType
            {
                get
                {
                    return _form1paymenttypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1PaymentType item info.
            /// </summary>
            [RepositoryItemInfo("205a490a-063f-4568-bda8-721c23f52dc3")]
            public virtual RepoItemInfo Form1PaymentTypeInfo
            {
                get
                {
                    return _form1paymenttypeInfo;
                }
            }

            /// <summary>
            /// The Form1Paymentreportentity item.
            /// </summary>
            [RepositoryItem("a38e0c6e-7dee-41f3-964b-bccf107e8849")]
            public virtual Ranorex.SelectTag Form1Paymentreportentity
            {
                get
                {
                    return _form1paymentreportentityInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1Paymentreportentity item info.
            /// </summary>
            [RepositoryItemInfo("a38e0c6e-7dee-41f3-964b-bccf107e8849")]
            public virtual RepoItemInfo Form1PaymentreportentityInfo
            {
                get
                {
                    return _form1paymentreportentityInfo;
                }
            }

            /// <summary>
            /// The Form1ProgramYear item.
            /// </summary>
            [RepositoryItem("bba8154e-9857-403f-9d85-c882e60d79f4")]
            public virtual Ranorex.SelectTag Form1ProgramYear
            {
                get
                {
                    return _form1programyearInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1ProgramYear item info.
            /// </summary>
            [RepositoryItemInfo("bba8154e-9857-403f-9d85-c882e60d79f4")]
            public virtual RepoItemInfo Form1ProgramYearInfo
            {
                get
                {
                    return _form1programyearInfo;
                }
            }

            /// <summary>
            /// The Form1ContinueButton item.
            /// </summary>
            [RepositoryItem("6a18858f-0bdb-4bce-bd69-3b56be5a80b1")]
            public virtual Ranorex.InputTag Form1ContinueButton
            {
                get
                {
                    return _form1continuebuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1ContinueButton item info.
            /// </summary>
            [RepositoryItemInfo("6a18858f-0bdb-4bce-bd69-3b56be5a80b1")]
            public virtual RepoItemInfo Form1ContinueButtonInfo
            {
                get
                {
                    return _form1continuebuttonInfo;
                }
            }

            /// <summary>
            /// The Form1CoveredRecipientType item.
            /// </summary>
            [RepositoryItem("4b3d5c1c-9786-4847-b79d-52ca981c31cc")]
            public virtual Ranorex.SelectTag Form1CoveredRecipientType
            {
                get
                {
                    return _form1coveredrecipienttypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1CoveredRecipientType item info.
            /// </summary>
            [RepositoryItemInfo("4b3d5c1c-9786-4847-b79d-52ca981c31cc")]
            public virtual RepoItemInfo Form1CoveredRecipientTypeInfo
            {
                get
                {
                    return _form1coveredrecipienttypeInfo;
                }
            }

            /// <summary>
            /// The Form1NrPhysicianFirst item.
            /// </summary>
            [RepositoryItem("d2460586-704a-4a20-b7c6-3b12f47fff08")]
            public virtual Ranorex.InputTag Form1NrPhysicianFirst
            {
                get
                {
                    return _form1nrphysicianfirstInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrPhysicianFirst item info.
            /// </summary>
            [RepositoryItemInfo("d2460586-704a-4a20-b7c6-3b12f47fff08")]
            public virtual RepoItemInfo Form1NrPhysicianFirstInfo
            {
                get
                {
                    return _form1nrphysicianfirstInfo;
                }
            }

            /// <summary>
            /// The Form1NrPhysicianLast item.
            /// </summary>
            [RepositoryItem("32173683-6b5d-4c95-ab40-b6195c89f2d8")]
            public virtual Ranorex.InputTag Form1NrPhysicianLast
            {
                get
                {
                    return _form1nrphysicianlastInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrPhysicianLast item info.
            /// </summary>
            [RepositoryItemInfo("32173683-6b5d-4c95-ab40-b6195c89f2d8")]
            public virtual RepoItemInfo Form1NrPhysicianLastInfo
            {
                get
                {
                    return _form1nrphysicianlastInfo;
                }
            }

            /// <summary>
            /// The Form1NrAddress1 item.
            /// </summary>
            [RepositoryItem("ba9847f0-1170-4467-838f-d137ee0da14e")]
            public virtual Ranorex.InputTag Form1NrAddress1
            {
                get
                {
                    return _form1nraddress1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrAddress1 item info.
            /// </summary>
            [RepositoryItemInfo("ba9847f0-1170-4467-838f-d137ee0da14e")]
            public virtual RepoItemInfo Form1NrAddress1Info
            {
                get
                {
                    return _form1nraddress1Info;
                }
            }

            /// <summary>
            /// The Form1NrState item.
            /// </summary>
            [RepositoryItem("0f589392-2158-47e7-b4a9-16c30ba7d28d")]
            public virtual Ranorex.SelectTag Form1NrState
            {
                get
                {
                    return _form1nrstateInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrState item info.
            /// </summary>
            [RepositoryItemInfo("0f589392-2158-47e7-b4a9-16c30ba7d28d")]
            public virtual RepoItemInfo Form1NrStateInfo
            {
                get
                {
                    return _form1nrstateInfo;
                }
            }

            /// <summary>
            /// The Form1RecipientZipCodeGnrl item.
            /// </summary>
            [RepositoryItem("a2840ba3-a5ff-4746-b3fe-c6e9f84280fc")]
            public virtual Ranorex.InputTag Form1RecipientZipCodeGnrl
            {
                get
                {
                    return _form1recipientzipcodegnrlInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1RecipientZipCodeGnrl item info.
            /// </summary>
            [RepositoryItemInfo("a2840ba3-a5ff-4746-b3fe-c6e9f84280fc")]
            public virtual RepoItemInfo Form1RecipientZipCodeGnrlInfo
            {
                get
                {
                    return _form1recipientzipcodegnrlInfo;
                }
            }

            /// <summary>
            /// The Form1NrPrimaryType item.
            /// </summary>
            [RepositoryItem("a0e0e6da-84ce-4164-a2aa-a219b578a803")]
            public virtual Ranorex.SelectTag Form1NrPrimaryType
            {
                get
                {
                    return _form1nrprimarytypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrPrimaryType item info.
            /// </summary>
            [RepositoryItemInfo("a0e0e6da-84ce-4164-a2aa-a219b578a803")]
            public virtual RepoItemInfo Form1NrPrimaryTypeInfo
            {
                get
                {
                    return _form1nrprimarytypeInfo;
                }
            }

            /// <summary>
            /// The SomePTag item.
            /// </summary>
            [RepositoryItem("c53a8161-9d2d-4280-aa84-cecd27b1790b")]
            public virtual Ranorex.PTag SomePTag
            {
                get
                {
                    return _someptagInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The SomePTag item info.
            /// </summary>
            [RepositoryItemInfo("c53a8161-9d2d-4280-aa84-cecd27b1790b")]
            public virtual RepoItemInfo SomePTagInfo
            {
                get
                {
                    return _someptagInfo;
                }
            }

            /// <summary>
            /// The Form1PhySpecGnrlInput item.
            /// </summary>
            [RepositoryItem("6b36eea0-2743-4a4e-b341-81ef49434573")]
            public virtual Ranorex.InputTag Form1PhySpecGnrlInput
            {
                get
                {
                    return _form1physpecgnrlinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1PhySpecGnrlInput item info.
            /// </summary>
            [RepositoryItemInfo("6b36eea0-2743-4a4e-b341-81ef49434573")]
            public virtual RepoItemInfo Form1PhySpecGnrlInputInfo
            {
                get
                {
                    return _form1physpecgnrlinputInfo;
                }
            }

            /// <summary>
            /// The FormRowGrid225 item.
            /// </summary>
            [RepositoryItem("6a3819bf-594c-4010-86cb-a6c108e242f4")]
            public virtual Ranorex.SpanTag FormRowGrid225
            {
                get
                {
                    return _formrowgrid225Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The FormRowGrid225 item info.
            /// </summary>
            [RepositoryItemInfo("6a3819bf-594c-4010-86cb-a6c108e242f4")]
            public virtual RepoItemInfo FormRowGrid225Info
            {
                get
                {
                    return _formrowgrid225Info;
                }
            }

            /// <summary>
            /// The Form1Nrlicense1 item.
            /// </summary>
            [RepositoryItem("16366e6b-790b-4c6d-bdf6-234f5d32a8ad")]
            public virtual Ranorex.InputTag Form1Nrlicense1
            {
                get
                {
                    return _form1nrlicense1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1Nrlicense1 item info.
            /// </summary>
            [RepositoryItemInfo("16366e6b-790b-4c6d-bdf6-234f5d32a8ad")]
            public virtual RepoItemInfo Form1Nrlicense1Info
            {
                get
                {
                    return _form1nrlicense1Info;
                }
            }

            /// <summary>
            /// The Form1RoleButton item.
            /// </summary>
            [RepositoryItem("c0c5f4fb-eed7-4c34-ad9c-63c2ce6a65a0")]
            public virtual Ranorex.InputTag Form1RoleButton
            {
                get
                {
                    return _form1rolebuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1RoleButton item info.
            /// </summary>
            [RepositoryItemInfo("c0c5f4fb-eed7-4c34-ad9c-63c2ce6a65a0")]
            public virtual RepoItemInfo Form1RoleButtonInfo
            {
                get
                {
                    return _form1rolebuttonInfo;
                }
            }

            /// <summary>
            /// The Form1ProductInd item.
            /// </summary>
            [RepositoryItem("e9e735b8-b5eb-4c5e-9ce9-0a23d349c708")]
            public virtual Ranorex.SelectTag Form1ProductInd
            {
                get
                {
                    return _form1productindInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1ProductInd item info.
            /// </summary>
            [RepositoryItemInfo("e9e735b8-b5eb-4c5e-9ce9-0a23d349c708")]
            public virtual RepoItemInfo Form1ProductIndInfo
            {
                get
                {
                    return _form1productindInfo;
                }
            }

            /// <summary>
            /// The Form1ContinueBtn item.
            /// </summary>
            [RepositoryItem("84a1741f-12dd-4e41-8043-ca6a53513e30")]
            public virtual Ranorex.InputTag Form1ContinueBtn
            {
                get
                {
                    return _form1continuebtnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1ContinueBtn item info.
            /// </summary>
            [RepositoryItemInfo("84a1741f-12dd-4e41-8043-ca6a53513e30")]
            public virtual RepoItemInfo Form1ContinueBtnInfo
            {
                get
                {
                    return _form1continuebtnInfo;
                }
            }

            /// <summary>
            /// The Form1NrTotalAmount item.
            /// </summary>
            [RepositoryItem("abe71b8a-6ec4-46b6-8081-0688171fc660")]
            public virtual Ranorex.InputTag Form1NrTotalAmount
            {
                get
                {
                    return _form1nrtotalamountInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrTotalAmount item info.
            /// </summary>
            [RepositoryItemInfo("abe71b8a-6ec4-46b6-8081-0688171fc660")]
            public virtual RepoItemInfo Form1NrTotalAmountInfo
            {
                get
                {
                    return _form1nrtotalamountInfo;
                }
            }

            /// <summary>
            /// The Form1PaymentDate item.
            /// </summary>
            [RepositoryItem("8b11133c-011e-4b2b-a613-dedb0589d23a")]
            public virtual Ranorex.InputTag Form1PaymentDate
            {
                get
                {
                    return _form1paymentdateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1PaymentDate item info.
            /// </summary>
            [RepositoryItemInfo("8b11133c-011e-4b2b-a613-dedb0589d23a")]
            public virtual RepoItemInfo Form1PaymentDateInfo
            {
                get
                {
                    return _form1paymentdateInfo;
                }
            }

            /// <summary>
            /// The Form1PaymentCount item.
            /// </summary>
            [RepositoryItem("558a31ec-9f39-4a43-b75a-d97944527b23")]
            public virtual Ranorex.InputTag Form1PaymentCount
            {
                get
                {
                    return _form1paymentcountInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1PaymentCount item info.
            /// </summary>
            [RepositoryItemInfo("558a31ec-9f39-4a43-b75a-d97944527b23")]
            public virtual RepoItemInfo Form1PaymentCountInfo
            {
                get
                {
                    return _form1paymentcountInfo;
                }
            }

            /// <summary>
            /// The Form1NrFormofPaymentorTransferofValue20 item.
            /// </summary>
            [RepositoryItem("bd290590-ae4f-46a5-adb3-46d894966c56")]
            public virtual Ranorex.SelectTag Form1NrFormofPaymentorTransferofValue20
            {
                get
                {
                    return _form1nrformofpaymentortransferofvalue20Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrFormofPaymentorTransferofValue20 item info.
            /// </summary>
            [RepositoryItemInfo("bd290590-ae4f-46a5-adb3-46d894966c56")]
            public virtual RepoItemInfo Form1NrFormofPaymentorTransferofValue20Info
            {
                get
                {
                    return _form1nrformofpaymentortransferofvalue20Info;
                }
            }

            /// <summary>
            /// The Form1NrNonResearchNatureofPaymentorTran item.
            /// </summary>
            [RepositoryItem("cd015676-7508-48bd-9440-60840913e498")]
            public virtual Ranorex.SelectTag Form1NrNonResearchNatureofPaymentorTran
            {
                get
                {
                    return _form1nrnonresearchnatureofpaymentortranInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrNonResearchNatureofPaymentorTran item info.
            /// </summary>
            [RepositoryItemInfo("cd015676-7508-48bd-9440-60840913e498")]
            public virtual RepoItemInfo Form1NrNonResearchNatureofPaymentorTranInfo
            {
                get
                {
                    return _form1nrnonresearchnatureofpaymentortranInfo;
                }
            }

            /// <summary>
            /// The Form1NrPhysicianOwnership item.
            /// </summary>
            [RepositoryItem("e488c9f1-6d34-466a-8ed1-80c16b2f6547")]
            public virtual Ranorex.InputTag Form1NrPhysicianOwnership
            {
                get
                {
                    return _form1nrphysicianownershipInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrPhysicianOwnership item info.
            /// </summary>
            [RepositoryItemInfo("e488c9f1-6d34-466a-8ed1-80c16b2f6547")]
            public virtual RepoItemInfo Form1NrPhysicianOwnershipInfo
            {
                get
                {
                    return _form1nrphysicianownershipInfo;
                }
            }

            /// <summary>
            /// The Form1NrThirdPartyPaymentRecipientIndica item.
            /// </summary>
            [RepositoryItem("4aaca5e0-54d2-4400-b508-ce666ca9c8ca")]
            public virtual Ranorex.SelectTag Form1NrThirdPartyPaymentRecipientIndica
            {
                get
                {
                    return _form1nrthirdpartypaymentrecipientindicaInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrThirdPartyPaymentRecipientIndica item info.
            /// </summary>
            [RepositoryItemInfo("4aaca5e0-54d2-4400-b508-ce666ca9c8ca")]
            public virtual RepoItemInfo Form1NrThirdPartyPaymentRecipientIndicaInfo
            {
                get
                {
                    return _form1nrthirdpartypaymentrecipientindicaInfo;
                }
            }

            /// <summary>
            /// The Form1CharityIndicator item.
            /// </summary>
            [RepositoryItem("63255ec9-6c01-4667-a442-86db50f2982d")]
            public virtual Ranorex.SelectTag Form1CharityIndicator
            {
                get
                {
                    return _form1charityindicatorInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1CharityIndicator item info.
            /// </summary>
            [RepositoryItemInfo("63255ec9-6c01-4667-a442-86db50f2982d")]
            public virtual RepoItemInfo Form1CharityIndicatorInfo
            {
                get
                {
                    return _form1charityindicatorInfo;
                }
            }

            /// <summary>
            /// The Form1NrResearchDelayinPublicationofRese item.
            /// </summary>
            [RepositoryItem("3ac563e5-4212-4c31-baf4-af636ac49d37")]
            public virtual Ranorex.SelectTag Form1NrResearchDelayinPublicationofRese
            {
                get
                {
                    return _form1nrresearchdelayinpublicationofreseInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrResearchDelayinPublicationofRese item info.
            /// </summary>
            [RepositoryItemInfo("3ac563e5-4212-4c31-baf4-af636ac49d37")]
            public virtual RepoItemInfo Form1NrResearchDelayinPublicationofReseInfo
            {
                get
                {
                    return _form1nrresearchdelayinpublicationofreseInfo;
                }
            }

            /// <summary>
            /// The Grid1000 item.
            /// </summary>
            [RepositoryItem("2c420f82-b57b-4e44-b1ed-6c7a81527279")]
            public virtual Ranorex.PTag Grid1000
            {
                get
                {
                    return _grid1000Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Grid1000 item info.
            /// </summary>
            [RepositoryItemInfo("2c420f82-b57b-4e44-b1ed-6c7a81527279")]
            public virtual RepoItemInfo Grid1000Info
            {
                get
                {
                    return _grid1000Info;
                }
            }

            /// <summary>
            /// The Form1Ns0x002fopenpayments0x002fOpen0x01 item.
            /// </summary>
            [RepositoryItem("e1db649a-041b-4a79-adfe-34382458b4b3")]
            public virtual Ranorex.SpanTag Form1Ns0x002fopenpayments0x002fOpen0x01
            {
                get
                {
                    return _form1ns0x002fopenpayments0x002fopen0x01Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Form1Ns0x002fopenpayments0x002fOpen0x01 item info.
            /// </summary>
            [RepositoryItemInfo("e1db649a-041b-4a79-adfe-34382458b4b3")]
            public virtual RepoItemInfo Form1Ns0x002fopenpayments0x002fOpen0x01Info
            {
                get
                {
                    return _form1ns0x002fopenpayments0x002fopen0x01Info;
                }
            }

            /// <summary>
            /// The Form1StLicGnrl item.
            /// </summary>
            [RepositoryItem("c00062db-705a-4a14-b838-debfa94c5600")]
            public virtual Ranorex.SelectTag Form1StLicGnrl
            {
                get
                {
                    return _form1stlicgnrlInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1StLicGnrl item info.
            /// </summary>
            [RepositoryItemInfo("c00062db-705a-4a14-b838-debfa94c5600")]
            public virtual RepoItemInfo Form1StLicGnrlInfo
            {
                get
                {
                    return _form1stlicgnrlInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("d9eb99d0-2659-45d6-9b7d-e09f233b8924")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("d9eb99d0-2659-45d6-9b7d-e09f233b8924")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The OPPSIT item.
            /// </summary>
            [RepositoryItem("21c8f28e-cbf5-4889-9469-f5f6a2be3276")]
            public virtual Ranorex.ATag OPPSIT
            {
                get
                {
                    return _oppsitInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OPPSIT item info.
            /// </summary>
            [RepositoryItemInfo("21c8f28e-cbf5-4889-9469-f5f6a2be3276")]
            public virtual RepoItemInfo OPPSITInfo
            {
                get
                {
                    return _oppsitInfo;
                }
            }

            /// <summary>
            /// The Form1NonresearchCountryPhy item.
            /// </summary>
            [RepositoryItem("a54196b7-bf21-47b7-b035-e85cfde21eca")]
            public virtual Ranorex.SelectTag Form1NonresearchCountryPhy
            {
                get
                {
                    return _form1nonresearchcountryphyInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Form1NonresearchCountryPhy item info.
            /// </summary>
            [RepositoryItemInfo("a54196b7-bf21-47b7-b035-e85cfde21eca")]
            public virtual RepoItemInfo Form1NonresearchCountryPhyInfo
            {
                get
                {
                    return _form1nonresearchcountryphyInfo;
                }
            }

            /// <summary>
            /// The Form1NrCity item.
            /// </summary>
            [RepositoryItem("f57646a7-39ca-4fef-81ee-3d8a112297eb")]
            public virtual Ranorex.InputTag Form1NrCity
            {
                get
                {
                    return _form1nrcityInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Form1NrCity item info.
            /// </summary>
            [RepositoryItemInfo("f57646a7-39ca-4fef-81ee-3d8a112297eb")]
            public virtual RepoItemInfo Form1NrCityInfo
            {
                get
                {
                    return _form1nrcityInfo;
                }
            }
        }

        /// <summary>
        /// The FirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("e7c2dfdf-c7b2-4aa9-902e-bd37bc07b046")]
        public partial class FirefoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _floridaInfo;
            RepoItemInfo _pleaseselectInfo;
            RepoItemInfo _virginiaInfo;

            /// <summary>
            /// Creates a new Firefox  folder.
            /// </summary>
            public FirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Firefox", "/form[@title='']", parentFolder, 30000, null, true, "e7c2dfdf-c7b2-4aa9-902e-bd37bc07b046", "")
            {
                _floridaInfo = new RepoItemInfo(this, "Florida", "?/?/listitem[@accessiblename='Florida']", 30000, null, "e13c0fcd-c4fd-4180-8b05-d19cc4efa27e");
                _pleaseselectInfo = new RepoItemInfo(this, "PleaseSelect", "list[@accessiblename='Please Select']", 30000, null, "c5b1c149-affe-4647-82aa-aa94d0c55d40");
                _virginiaInfo = new RepoItemInfo(this, "Virginia", ".//listitem[@accessiblename='Virginia']", 30000, null, "2a258d09-f516-49b0-b13a-65f5643093bd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e7c2dfdf-c7b2-4aa9-902e-bd37bc07b046")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e7c2dfdf-c7b2-4aa9-902e-bd37bc07b046")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Florida item.
            /// </summary>
            [RepositoryItem("e13c0fcd-c4fd-4180-8b05-d19cc4efa27e")]
            public virtual Ranorex.ListItem Florida
            {
                get
                {
                    return _floridaInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Florida item info.
            /// </summary>
            [RepositoryItemInfo("e13c0fcd-c4fd-4180-8b05-d19cc4efa27e")]
            public virtual RepoItemInfo FloridaInfo
            {
                get
                {
                    return _floridaInfo;
                }
            }

            /// <summary>
            /// The PleaseSelect item.
            /// </summary>
            [RepositoryItem("c5b1c149-affe-4647-82aa-aa94d0c55d40")]
            public virtual Ranorex.List PleaseSelect
            {
                get
                {
                    return _pleaseselectInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The PleaseSelect item info.
            /// </summary>
            [RepositoryItemInfo("c5b1c149-affe-4647-82aa-aa94d0c55d40")]
            public virtual RepoItemInfo PleaseSelectInfo
            {
                get
                {
                    return _pleaseselectInfo;
                }
            }

            /// <summary>
            /// The Virginia item.
            /// </summary>
            [RepositoryItem("2a258d09-f516-49b0-b13a-65f5643093bd")]
            public virtual Ranorex.ListItem Virginia
            {
                get
                {
                    return _virginiaInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Virginia item info.
            /// </summary>
            [RepositoryItemInfo("2a258d09-f516-49b0-b13a-65f5643093bd")]
            public virtual RepoItemInfo VirginiaInfo
            {
                get
                {
                    return _virginiaInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
